# Generated by Django 5.1.3 on 2025-02-24 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='category',
    #         name='slug',
    #         field=models.SlugField(blank=True, max_length=255, unique=True),
    #     ),
    #     migrations.AlterField(
    #         model_name='category',
    #         name='name',
    #         field=models.CharField(max_length=255, unique=True),
    #     ),
    #     migrations.CreateModel(
    #         name='CategoryOffer',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('offer_name', models.CharField(max_length=255)),
    #             ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], max_length=50)),
    #             ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
    #             ('minimum_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
    #             ('start_date', models.DateTimeField()),
    #             ('end_date', models.DateTimeField()),
    #             ('is_active', models.BooleanField(default=True)),
    #             ('is_available', models.BooleanField(default=True)),
    #             ('created_at', models.DateTimeField(auto_now_add=True)),
    #             ('updated_at', models.DateTimeField(auto_now=True)),
    #             ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='category.category')),
    #         ],
    #         options={
    #             'verbose_name': 'Category Offer',
    #             'verbose_name_plural': 'Category Offers',
    #         },
    #     ),
    # ]
    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], max_length=50)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='category.category')),
            ],
            options={
                'verbose_name': 'Category Offer',
                'verbose_name_plural': 'Category Offers',
            },
        ),
    ]
