# Generated by Django 5.1.3 on 2025-03-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='minimum_purchase_amount',
        ),
    ]
