# Generated by Django 5.1.3 on 2025-02-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermain_payment_id_ordermain_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment_Pending', 'Payment Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return_Initiated', 'Return Initiated'), ('Return_Approved', 'Return Approved'), ('Return_Rejected', 'Return Rejected')], default='Pending', max_length=20),
        ),
    ]
