# Generated by Django 5.1.3 on 2025-02-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_is_returned_returnrequest_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermain',
            name='category_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordermain',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordermain',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordermain',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
