# Generated by Django 5.1.3 on 2025-02-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordermain_category_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermain',
            name='category_discount',
        ),
        migrations.RemoveField(
            model_name='ordermain',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='ordermain',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='ordermain',
            name='product_discount',
        ),
    ]
