# Generated by Django 5.1.3 on 2025-02-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordermain_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Return Requested'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
